### ISSUE TITLE
Interpretation of outputs

### ISSUE THREAD

**Issue by Kaonashi22** [sct-pipeline/spine-park#11]
version: 9d780cc

Here is an example of output for one subject. If I understood well, values are averaged across vertebral levels, with the column "D" indicating the index of the averaged slices. In column E ("VertLevel"), levels are numbered from 12 to 2 in descending order. What's the anatomical correspondence ? 

When running the script on multiple subjects, should I get one file per subject or all subjects in one file?

[MTR_in_WM.csv](https://github.com/sct-pipeline/spine-park/files/14450840/MTR_in_WM.csv)

**Comment by jcohenadad** [comment]
I know this can be confusing. In the example below:

<img width="465" alt="image" src="https://github.com/sct-pipeline/spine-park/assets/2482071/188668b7-4366-4285-89c1-8458403a82f3">

- `VertLevel`: Vertebral level, using the [labeling convention of SCT](https://spinalcordtoolbox.com/user_section/tutorials/vertebral-labeling/labeling-conventions.html). For example, "8" means T1.
- `Slice (I->S)`: The axial slices associated with the vertebral level
- `MAP()`: The extracted metric (what you want), averaged using the maximum a posteriori method
