### ISSUE TITLE
ERROR for UNI images: Metric data and labels DO NOT HAVE SAME DIMENSIONS.

### ISSUE THREAD

**Issue by Kaonashi22** [sct-pipeline/spine-park#12]
Version 1b378e0:

The UNI images are now segmented and registered to the template in a reasonable time, but the the T1 values are not extracted. Here is the error:

sct_extract_metric -i sub-DEV148Sujet01_T1map.nii.gz -f label_T1/atlas -l 51 -vert 2:12 -vertfile label_T1/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /dagher/dagher12/lydia12/Results/results/T1_in_WM.csv -append 1
--
Load metric image...
ERROR: Metric data and labels DO NOT HAVE SAME DIMENSIONS.

**Comment by jcohenadad** [comment]
See: https://github.com/sct-pipeline/spine-park/pull/8#issuecomment-1971439126

Fixed in https://github.com/sct-pipeline/spine-park/pull/8/commits/12624513289de59866abbb6c7735f976d56e3879
