### ISSUE TITLE
QC display

### ISSUE THREAD

**Issue by Kaonashi22** [sct-pipeline/spine-park#13]
On the QC web page, the flags  "Pass ✅ | Fail ❌ | Artifact ⚠️"  are not provided for the processed images

![3](https://github.com/sct-pipeline/spine-park/assets/155473122/f3159acc-8995-4f74-b9d2-740496e14ef6)

**Comment by jcohenadad** [comment]
The flags are to be created by a human (ie: you), this is precisely the purpose of this quality control step.

**Comment by Kaonashi22** [comment]
I see, I thought there was some kind of automated QC.
Is there like a template generated by the QC where I could add QC flags?
________________________________

**Comment by jcohenadad** [comment]
> Is there like a template generated by the QC where I could add QC flags?

I'm not sure I understand the question.

**Comment by Kaonashi22** [comment]
I was wondering if I could add flags on the website; I found out how to do it


________________________________
