### ISSUE TITLE
Create function to aggregate DWI metrics across chunks

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/spine-park#14]
Given that some DWI chunks overlap, the code currently produces CSV with the same vertebral level covered by two adjacent chunks. Example below:
<img width="1225" alt="image" src="https://github.com/sct-pipeline/spine-park/assets/2482071/f4dc7941-8ebd-43dd-b15a-be166165f3ed">

One elegant solution would be to take this CSV as input, and aggregate the lines that share the same vertebral level. The aggregation would be done using weighted average, the weighting being driven by the column "Size [vox]".

**Comment by Kaonashi22** [comment]
Any progress on that?

**Comment by jcohenadad** [comment]
sorry-- i will try to work on it tomorrow

**Comment by Kaonashi22** [comment]
No worries!
