### ISSUE TITLE
Conversion of diffusion images to BIDS format

### ISSUE THREAD

**Issue by Kaonashi22** [sct-pipeline/spine-park#16]
I've noticed that the naming of the diffusion images (3 chunks from skull base to T5) is not consistent across subjects. For example, for the first subject, "chunk1" corresponds to the lower volume, "chunk2" to the upper volume, and "chunk3" to the middle. The order is different when I look at other subjects.
The original diffusion volumes were acquired from top to bottom, and were named accordingly, for example, "S2", "S3", "S4" or "S4", "S5", "S6".

**Comment by jcohenadad** [comment]
@Kaonashi22 I'm working on it right now

**Comment by jcohenadad** [comment]
@Kaonashi22 I fixed this issue in #18 (already merged to the 'main' branch). Could you please `git pull` your local repository, re-run the conversion, and let me know if this issue is solved on your end?

**Comment by Kaonashi22** [comment]
The issue is solved, thank you!
