### ISSUE TITLE
Add feature to use manually corrected labels on T2w data

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/spine-park#17]
As per #15, the script should be modified to use manually corrected labels if they exist. The labels should be located under `./derivatives/labels/` and have the suffix `_seg` on the T2w data.

**Comment by jcohenadad** [comment]
Ah! It's already implemented 😅 

And it is working. I tested it with a derivatives/labels T2w segmentation mask in one subjects, and the script used it:

~~~
👉 Processing: sub-BB277_T2

Looking for manual segmentation: /Users/julien/temp/Lydia/data_small/derivatives/labels/sub-BB277/anat/sub-BB277_T2_seg.nii.gz
Found! Using manual segmentation.
~~~

Closing

**Comment by jcohenadad** [comment]
@Kaonashi22 you can already use the manually corrected segmentations for your project.

**Comment by Kaonashi22** [comment]
Version of the script: 78129ca

Regarding the issue about segmentations being overwritten, here is the path to the input directory: /dagher/dagher12/lydia12/SPINE_park/CENIR_ICEBERG_BIDS. There is no "derivatives" folder. I don't think the script generates this folder (and moves the segmentations there).

**Comment by jcohenadad** [comment]
> There is no "derivatives" folder.

Ah, so that's the problem. The manual segmentations should be located under a specific derivatives/ folder as per: https://github.com/sct-pipeline/spine-park/issues/17#issue-2226531151

I'll update the README with a clear example--

**Comment by Kaonashi22** [comment]
So, I should create the derivatives folder myself and move the segmentation files there?

**Comment by jcohenadad** [comment]
yes, or, much better, use an automatic procedure that also creates the JSON file (important for tracking provenance): https://github.com/spinalcordtoolbox/manual-correction

we covered this in the latest SCT course (maybe @valosekj you know the exact passage in the video/slides)

**Comment by valosekj** [comment]
> we covered this in the latest SCT course (maybe @valosekj you know the exact passage in the video/slides)

Yes! The passage about manual corrections starts at  [6:44:26](https://youtu.be/hTbJo8GO5IU?si=DImu-d6AWB8gKlVl&t=24266).
We also have a step-by-step example of SC segmentation corrections on [our wiki](https://github.com/spinalcordtoolbox/manual-correction/wiki#segmentation-masks-scgm-segmentation-masks-mssci-lesion-masks).
There is also this [YT tutorial](https://www.youtube.com/watch?v=lB-F8WOHGeg&t=375s) on correcting segmentations across multiple subjects. However, it is slightly obsolete (we now use https://github.com/spinalcordtoolbox/manual-correction instead of the script described in the video). But the overall concept is the same.

Let me know if you need any further info; I will be happy to help!

**Comment by Kaonashi22** [comment]
Thanks @valosekj  and @jcohenadad.
I actually used the "[manual-correction](https://github.com/spinalcordtoolbox/manual-correction)" module to correct the masks. In the end, the derivatives folder only includes subjects with these corrected masks, not those that didn't required a manual correction (as they were not  in the yml file). So their segmentations are overwritten. 
I guess I should manually export  the masks of these subjects to the derivatives folder as well.

**Comment by Kaonashi22** [comment]
Would you know if the segmentations are identical between different runs? I already did the QC and manual corrections on previous segmentations. After reruning the pipeline, I obtained new segmentations, and I'm wondering whether I need to redo the QC and corrections.

**Comment by Kaonashi22** [comment]
I see, that's clearer, thanks!

**Comment by valosekj** [comment]
> In the end, the derivatives folder only includes subjects with these corrected masks

Yes, this is correct! The [manual-correction](https://github.com/spinalcordtoolbox/manual-correction) module saves only the manually corrected masks under `derivatives`.

> , not those that didn't required a manual correction (as they were not in the yml file). 

Just for info. If you really needed to save masks that don't require manual correction under `derivatives`, you could you the `-add-seg-only` argument (described [here](https://github.com/spinalcordtoolbox/manual-correction/blob/main/manual_correction.py#L230-L235)). This argument will copy masks that _**aren't**_ in `-config` list (i.e., those that didn't require correction) into `derivatives`.
This might be useful, for example, if you wanted to store masks generated by a specific algorithm version.
