### ISSUE TITLE
Add call to SPINEPS in batch_processing.sh

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/spine-park#21]
@NathanMolinier

**Comment by Kaonashi22** [comment]
@jcohenadad and @NathanMolinier, any updates on how to call SPINEPS in the script? I've successfully installed the toolbox.

**Comment by Kaonashi22** [comment]
Great, thank you!

**Comment by NathanMolinier** [comment]
Sorry for the slight delay, but I'm writing a full documentation to make sure that this pipeline reproducible. Everything should be ready by the end of the day !

**Comment by NathanMolinier** [comment]
Here is my [documentation](https://github.com/ivadomed/utilities/blob/nm/use_spineps_vert_labeling/quick_start_guides/use_SPINEPS_for_discs_labeling.md) ! If it's not clear feel free to give me feedback. And I can give you more help. 

If you want, you can deal with the installation of the conda environment and I can modify the [batch_processing.sh](https://github.com/sct-pipeline/spine-park/blob/702120be3efeb4e3023ae8b3299ebe4b7061bf74/batch_processing.sh#L58C1-L59C1) script.

Also, you mentioned that you already managed to install spineps, so you only need to perform these last [steps](https://github.com/ivadomed/utilities/blob/nm/use_spineps_vert_labeling/quick_start_guides/use_SPINEPS_for_discs_labeling.md#discs-labeling-installation).

**Comment by Kaonashi22** [comment]
Thank you!
Yes, I already installed SPINEPS; I'll look at these last steps.

I sent you a couple of subjects you could use for a test.
________________________________

**Comment by NathanMolinier** [comment]
Yes ! I'm on it ! I will update you when I will be done

**Comment by NathanMolinier** [comment]
I ran this script:
<details>
<summary>bash script</summary>

```bash
label_with_spineps(){
    local img_path=$(realpath "$1")
    local out_path="$2"
    local contrast="$3"
    local img_name="$(basename "$img_path")"
    (
        # Create temporary directory
        tmpdir="$(mktemp -d)"
        echo "$tmpdir" was created

        # Copy image to temporary directory
        tmp_img_path="${tmpdir}/${img_name}"
        cp "$img_path" "$tmp_img_path"

        # Activate conda env
        eval "$(conda shell.bash hook)" #source /usr/local/miniforge3/etc/profile.d/conda.sh
        conda activate spineps

        # Select semantic weights
        if [ "$contrast" = "t1" ];
            then semantic=t1w_segmentor;
            else semantic=t2w_segmentor_2.0;
        fi
        
        # Run SPINEPS on image
        spineps sample -i "$tmp_img_path" -model_semantic "$semantic" -model_instance inst_vertebra_2.0 -dn derivatives
        
        # Run vertebral labeling with SPINEPS vertebrae prediction
        vert_path="$(echo ${tmpdir}/derivatives/*_seg-vert_msk.nii.gz)"
        python3 "${IVADOMED_UTILITIES_REPO}/training_scripts/generate_discs_labels_with_SPINEPS.py" --path-vert "$vert_path" --path-out "$out_path"

        # Remove temporary directory
        rm -r "$tmpdir"
        echo "$tmpdir" was removed

        # Deactivate conda environment
        conda deactivate
    )
}

BIDS_PATH="/home/GRAMES.POLYMTL.CA/p118739/data_nvme_p118739/data/datasets/dataset-spark/Test_sample"
QC_PATH="/home/GRAMES.POLYMTL.CA/p118739/data_nvme_p118739/data/datasets/dataset-spark/Test_sample/qc"

for file in $(echo "${BIDS_PATH}/sub*/anat/sub*T2*.nii.gz");do     
        echo Dealing with file: "$file"
        fname=$(basename "$file")
        out_name="${fname/T2.nii.gz/T2_label-discs_dlabel.nii.gz}"
        in_dir=$(dirname "$file")
        out_dir="${in_dir//Test_sample/Test_sample/derivatives/labels}"
        out_file="${out_dir}/${out_name}"
        label_with_spineps "$file" "$out_file" "t2"
        sct_qc -i "$file" -s "$out_file" -p sct_label_vertebrae -qc "$QC_PATH"
done
```

</details>

And got really good discs labels: can I share the QC in the issue ?

**Comment by Kaonashi22** [comment]
Great, thanks!
Sure, you can share the QC in the issue or send it by mail
________________________________

**Comment by NathanMolinier** [comment]
Here is the [qc.zip](https://github.com/sct-pipeline/spine-park/files/15042327/qc.zip) ! Also, I contacted the author of SPINEPS to mention the segmentation problem of one of the subject and he sent me new updated model weights that seemed to have solved the issue.

The subject sub-AP211 has one wrong label at the bottom of the image.

**Comment by Kaonashi22** [comment]
That's very good, thanks for your work!
I think we're almost done with the pipeline now :)

**Comment by jcohenadad** [comment]
@NathanMolinier as mentioned [earlier](https://github.com/sct-pipeline/spine-park/issues/21#issuecomment-2060216682), it would help @Kaonashi22 if you could write the appropriate syntax to call SPINEPS, ie: replace this line:

https://github.com/sct-pipeline/spine-park/blob/702120be3efeb4e3023ae8b3299ebe4b7061bf74/batch_processing.sh#L58

Thanks!

**Comment by NathanMolinier** [comment]
I just pushed the code but I realized that I completely forgot to create a branch before pushing... I hope it is not a problem.

**Comment by jcohenadad** [comment]
@Kaonashi22 can you try the latest version 88b03cd2f5110a598ae0961c381533b65a23dfbd from @NathanMolinier and let us know how it works?

**Comment by Kaonashi22** [comment]
Sure, I'll let you know

________________________________

**Comment by Kaonashi22** [comment]
I get this error when I run the last version of the script. I don't think that's a problem of space because I have enough space storage and it occurs even when running on a single subject. 
[err.batch_processing_sub-BB277.log](https://github.com/sct-pipeline/spine-park/files/15052462/err.batch_processing_sub-BB277.log)

**Comment by jcohenadad** [comment]
The code assumes it is possible to create a file in the `/tmp` directory:
````
mktemp: failed to create directory via template ‘/tmp/tmp.XXXXXXXXXX’: No space left on device
````

@NathanMolinier is this your code or SPINEPS? If the latter, this seems tricky to address (because it will impact SPINEPS, requires thorough testing, etc.).

**Comment by NathanMolinier** [comment]
Yes it is my code, I am creating a temporary directory to store all the files generated using spineps and perform my labeling, see:
https://github.com/sct-pipeline/spine-park/blob/88b03cd2f5110a598ae0961c381533b65a23dfbd/batch_processing.sh#L46

**Comment by jcohenadad** [comment]
> Maybe we could create a folder, run the inference then remove its content ?

this is already what you do (ie: `mktemp` does create a folder). What you probably meant is: create a folder in the current directory (ie: where the script is running)? If so, then yes, that would be an option. Make sure to call the folder with a unique name. Tagging @joshuacwnewton @mguaypaq in case they have a better idea.

**Comment by NathanMolinier** [comment]
>  create a folder in the current directory (ie: where the script is running)

Yes that was what I meant indeed

**Comment by joshuacwnewton** [comment]
I'm not sure I understand the difference between using `/tmp` vs. using the current directory. 

> ```
> mktemp: failed to create directory via template ‘/tmp/tmp.XXXXXXXXXX’: No space left on device
> ```

Won't this be an issue no matter where the folder is created? If the user has space issues, then that's sort of out of our hands, hehe.

Unless you're suggesting that the current directory will be on a different drive than `/tmp` (with more space)?

**Comment by jcohenadad** [comment]
> Unless you're suggesting that the current directory will be on a different drive than /tmp (with more space)?

I think this is what's happening unfortunately: https://github.com/sct-pipeline/spine-park/issues/21#issuecomment-2068081051

**Comment by joshuacwnewton** [comment]
Ahhh, right!! --> https://ubuntuforums.org/showthread.php?t=2210977

> Do you have enough spare inodes ? Running out of inodes can also cause the error you are seeing.
> Run: 
> ```
> df -i
> ```
> for the number of inodes, the number used and the number free.

For a baseline value, this is what I see on my system:

```
dot|joshua@monarch:~$ df -i
Filesystem       Inodes   IUsed    IFree IUse% Mounted on
tmpfs           2013837    1462  2012375    1% /run
efivarfs              0       0        0     - /sys/firmware/efi/efivars
/dev/nvme0n1p2 15597568 1117193 14480375    8% /
tmpfs           2013837       1  2013836    1% /dev/shm
tmpfs           2013837       6  2013831    1% /run/lock
tmpfs           2013837       7  2013830    1% /run/qemu
/dev/nvme0n1p1        0       0        0     - /boot/efi
tmpfs            402767     166   402601    1% /run/user/1000
```

If this is indeed the case, I wonder if this is also the cause of the space-related issues we saw elsewhere for @Kaonashi22's system?

**Comment by Kaonashi22** [comment]
Thank you for brainstorming on my case! 
The data is located on the server of the institute. This is the storage space I have:

Filesystem                                       Size  Used **Avail** Use%   Mounted on
_nfs.isi.bic.mni.mcgill.ca:/dagher12   10T  9.9T  **146G**  99% /dagher/dagher12
nfs.isi.bic.mni.mcgill.ca:/dagher11   20T   20T  **304G**  99% /dagher/dagher11_

Do you think this is enough in theory to run the analysis on ~60subjects with the four contrasts (T2, MT, MP2RAGE, dwi)? What is weird is that it doesn't even work on a single subject with the spineps function.

When I type df -i, it returns

_Filesystem                               Inodes       IUsed     IFree IUse% Mounted on
udev                                    4088078         616   4087462    1% /dev
tmpfs                                   4094868        1309   4093559    1% /run
/dev/sda1                               4046848     1326443   2720405   33% /
tmpfs                                   4094868         106   4094762    1% /dev/shm
tmpfs                                   4094868          13   4094855    1% /run/lock
tmpfs                                   4094868          16   4094852    1% /sys/fs/cgroup
/dev/sda8                              23445504     4518058  18927446   20% /export01
/dev/sda7                                142560         210    142350    1% /tmp
/dev/sda6                                 65536          93     65443    1% /var/tmp
tmpfs                                   4094868           1   4094867    1% /run/qemu
/dev/md9                              390674816     2321873 388352943    1% /export02
tubal:/home                           429496704    21533085 407963619    6% /home/bic
tmpfs                                   4094868          84   4094784    1% /run/user/3471
nfs.isi.bic.mni.mcgill.ca:/dagher8  10737418240 10730522384   6895856  100% /dagher/dagher8
**nfs.isi.bic.mni.mcgill.ca:/dagher12 21474836480 21169669904 305166576   99% /dagher/dagher12
nfs.isi.bic.mni.mcgill.ca:/dagher11 42949672960 42312360736 637312224   99% /dagher/dagher11**_
I'm using the two last locations; it might be the problem then...

@jcohenadad , I'll email the IT and cc you

**Comment by Kaonashi22** [comment]
I also tried to install the SCT on Compute Canada to avoid these storage issues, but I didn't succeed

**Comment by joshuacwnewton** [comment]
> I also tried to install the SCT on Compute Canada to avoid these storage issues, but I didn't succeed

If it's not too much to ask, could you please [open a new issue on the SCT repo](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/new?assignees=&labels=&projects=&template=bug_report.md) for this? (I am happy to help debug installations of SCT on CC, and having the install log would be greatly appreciated.)

**Comment by Kaonashi22** [comment]
Sure, I'll try to reinstall again and open a new issue

**Comment by joshuacwnewton** [comment]
> @jcohenadad , I'll email the IT and cc you

The email exchange ended with McGill's IT analyst mentioning:

> since the storage issue is resolved, I will close this ticket.

I'm not 100% sure if this is true (since the separate issue #24 popped up during debugging, potentially hiding the space issues?), but I thought I would mention it on this issue as a small update.

**Comment by jcohenadad** [comment]
Given the difficulty in getting the GPU to work on the McGill server, and anticipating the difficulty in installing SCT and SPINEPS on the Compute Canada server (not mentioning the added complexity of the SLURM queuing system and getting both CPU and GPU ressource, with enough RAM), I am wondering if doing the manual labeling would not be faster? With https://github.com/spinalcordtoolbox/manual-correction it literally takes about 15s per subject to label all discs, so for 200 subjects it's about 50min. Compared to the multiple days spent trying to figure out how to install and run SPINEPS, etc. I really think labeling should be done manually for this project to move forward efficiently.

**Comment by Kaonashi22** [comment]
I was also coming to this conclusion... Could you please indicate which version of the script I can use (I'm a bit lost between the different versions !)? 
I think there were still two ongoing issues: the generation of all diffusion maps (currently only FA is being generated) and a loop for calculating metrics in all tracts.
I'll also post soon the bugs I got when trying to install the SCT on Compute Canada

**Comment by jcohenadad** [comment]
> I was also coming to this conclusion... Could you please indicate which version of the script I can use (I'm a bit lost between the different versions !)?

Always use the [latest](https://github.com/sct-pipeline/spine-park/blob/main/batch_processing.sh)

I still need to remove SPINEPS from the processing script though: https://github.com/sct-pipeline/spine-park/issues/26

> I think there were still two ongoing issues: the generation of all diffusion maps (currently only FA is being generated)

issue created https://github.com/sct-pipeline/spine-park/issues/25

> and a loop for calculating metrics in all tracts. 

https://github.com/sct-pipeline/spine-park/issues/10

> I'll also post soon the bugs I got when trying to install the SCT on Compute Canada

thx!

**Comment by jcohenadad** [comment]
We decided to remove SPINEPS deps until it is possible to run inference on CPU https://github.com/Hendrik-code/spineps/issues/10
