### ISSUE TITLE
Issue with the segmentation of dwi images `sub-DEV205Sujet09`

### ISSUE THREAD

**Issue by Kaonashi22** [sct-pipeline/spine-park#38]
For one subject, the aorta has been segmented on the dwi images, chunk 3.
![image](https://github.com/sct-pipeline/spine-park/assets/155473122/0f9e3abf-6496-4f96-a766-9eaf28ee10cc)

Here is the position of the WM template after registration ot the template.
![image](https://github.com/sct-pipeline/spine-park/assets/155473122/bca1ebb7-8b99-45a6-a686-908e9b1059ea)

I was using this SCT version when I had the issue: git version 2.25.1
And this script version: 
![image](https://github.com/sct-pipeline/spine-park/assets/155473122/65cfc670-100e-408a-8116-f8bf62bbd9ad)

@jcohenadad , I'll send you the data by email

**Comment by jcohenadad** [comment]
I've updated the title to include the subject name.

I've ran the processing using script version 46499f4fa7e7ad2bf6663763736af9863461cc58, SCT `git-master-9e1f65b86902cb237d5f79058a4623eed2d2c8eb` and these derivatives: [sub-DEV169Sujet03.zip](https://github.com/user-attachments/files/15919138/sub-DEV169Sujet03.zip)

I did not observe the issue reported by @Kaonashi22 
- [sct_run_batch_log.txt](https://github.com/user-attachments/files/15919126/sct_run_batch_log.txt)
- [qc.zip](https://github.com/user-attachments/files/15919124/qc.zip)

@Kaonashi22 can you please try with the derivatives I've attached, and upload the generated QC report and log file please.

**Comment by Kaonashi22** [comment]
Sorry, I forgot you send you my derivatives for this subject:
[sub-DEV205Sujet09.zip](https://github.com/user-attachments/files/15920702/sub-DEV205Sujet09.zip)

I am rerunning the analyses with your derivatives ; I'll let you know what I find.

**Comment by Kaonashi22** [comment]
The spinal cord segmentation is also slighting different between the two runs :
-"seg_1" : first segmentation with the issue
-"seg_2" : last segmentation without the issue

[seg_2_sub-DEV205Sujet09_chunk-3_DWI_dwi_mean_seg.nii.gz](https://github.com/user-attachments/files/15974206/seg_2_sub-DEV205Sujet09_chunk-3_DWI_dwi_mean_seg.nii.gz)
[Uploading sub-DEV205Sujet09_chunk-3_DWI_dwi_mean.nii.gz…]()
[seg_1_sub-DEV205Sujet09_chunk-3_DWI_dwi_mean_seg.nii.gz](https://github.com/user-attachments/files/15974219/seg_1_sub-DEV205Sujet09_chunk-3_DWI_dwi_mean_seg.nii.gz)

**Comment by jcohenadad** [comment]
> Do you think I can use my derivatives from my previous run (two months ago) when I run the pipeline with the updated script and SCT version? I did an extensive manual correction on the segmentation masks.

Yes, absolutely. You can reuse the segmentations you've already corrected if you are happy with them.

**Comment by jcohenadad** [comment]
I assume we can close this issue now
