### ISSUE TITLE
sct_qc: error: argument -p: invalid choice: 'sct_deepseg'

### ISSUE THREAD

**Issue by Kaonashi22** [sct-pipeline/spine-park#39]
Using the last version of the script ([8e66fb4](https://github.com/sct-pipeline/spine-park/commit/8e66fb444aa1a887babaf2fc2d56b966acbe801e)) and the updated SCT, I had this error for several subjects:

![image](https://github.com/sct-pipeline/spine-park/assets/155473122/102f165a-5911-4fbb-9596-0cc547c35bf8)
[err.batch_processing_sub-DEV159Sujet02.log](https://github.com/user-attachments/files/15914836/err.batch_processing_sub-DEV159Sujet02.log)

**Comment by Kaonashi22** [comment]
Of note, the "label-disc" files are located in ${PATH_DATA}"/derivatives/labels/"${SUBJECT}"/anat/"

**Comment by jcohenadad** [comment]
I've updated the title to be specific to the error (easier to search in the long term)
