### ISSUE TITLE
Wrong path to derivatives of dwi masks

### ISSUE THREAD

**Issue by Kaonashi22** [sct-pipeline/spine-park#40]
The script looks for the derivatives of dwi masks in this folder
FILESEGMANUAL="${PATH_DATA}"/derivatives/labels/"${SUBJECT}"/anat/"${FILESEG}".nii.gz
I guess there should be another path pointing to "dwi".

Otherwise, the pipeline is working well!

**Comment by jcohenadad** [comment]
Oops! Good catch. Problematic line to adapt:
https://github.com/sct-pipeline/spine-park/blob/46499f4fa7e7ad2bf6663763736af9863461cc58/batch_processing.sh#L90

This will be an easy fix
